version: '3'

services:
  puppet:
    hostname: puppet-master
    container_name: puppet-master
    image: puppet/puppetserver
    ports:
      - "8140:8140"
    environment:
      - PUPPETSERVER_HOSTNAME=puppet.puppet-master
      - DNS_ALT_NAMES=puppet,puppet.puppet-master
      - PUPPETDB_SERVER_URLS=https://puppetdb.puppet-master:8081
    volumes:
      - ./volumes/code:/etc/puppetlabs/code/
      - ./volumes/puppet:/etc/puppetlabs/puppet/
      - ./volumes/serverdata:/opt/puppetlabs/server/data/puppetserver/
    dns_search: puppet.puppet-master
    networks:
      puppet:
        aliases:
         - puppet.puppet-master
         - puppet-master
         - puppet
#    network_mode: 'host'


  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    expose:
      - 5432
    volumes:
      - ./volumes/puppetdb-postgres/data:/var/lib/postgresql/data
      - ./postgres-custom:/docker-entrypoint-initdb.d
    dns_search: puppet.puppet-master
    networks:
      puppet:
        aliases:
         - postgres.puppet-master
         - postgres

  puppetdb:
    hostname: puppetdb.puppet-master
    image: puppet/puppetdb
    environment:
      - CERTNAME=puppetdb.puppet-master
      #- PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-true}
      # This name is an FQDN so the short name puppet doesn't collide outside compose network
      - PUPPETSERVER_HOSTNAME=puppet.puppet-master
      - PUPPETDB_POSTGRES_HOSTNAME=postgres.puppet-master
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
    depends_on:
      - postgres
      - puppet
    volumes:
      - ./volumes/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
      - ./volumes/puppetdb/certs:/opt/puppetlabs/server/data/puppetdb/certs
      - ./volumes/puppetdb/logs:/opt/puppetlabs/server/data/puppetdb/logs
    dns_search: puppet.puppet-master
    networks:
      puppet:
        aliases:
         - puppetdb.puppet-master
         - puppetdb
#    network_mode: 'host'


  puppetboard:
    hostname: puppetboard.puppet-master
    image: puppet/puppetboard
    environment:
     - PUPPETDB_HOST=puppetdb.puppet-master
     #- PUPPETDB_PORT=8081
    ports:
      - "8008:8000"
    networks:
      puppet:
        aliases:
         - puppetboard.puppet-master
         - puppetboard

#    network_mode: 'host'

networks:
  puppet:
    driver: bridge